# Generated by Django 6.0 on 2026-06-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.1, help_text='Tax rate as decimal, e.g. 0.10 = 10%', max_digits=5)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=50.0, help_text='Order subtotal above which shipping is free', max_digits=10)),
                ('default_shipping_cost', models.DecimalField(decimal_places=2, default=5.0, help_text='Flat shipping cost when below the free threshold', max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('currency_symbol', models.CharField(default='₣', max_length=5)),
                ('store_name', models.CharField(default='NextShopSphere', max_length=100)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('low_stock_alert_email', models.EmailField(blank=True, help_text='Email to notify when a product goes below low_stock_threshold', max_length=254)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
